name: Snapshot
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: {}

jobs:
  snapshot:
    name: Snapshot
    if: github.repository_owner == 'floydspace'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/setup
      - name: Build package
        run: pnpm run build
      - name: Create snapshot
        id: snapshot
        run: pnpx pkg-pr-new@0.0.28 publish --pnpm --comment=off ./packages/*
